import Link from "next/link";
import PageShell,{PageHero} from "../SiteChrome";
import BrushHeading from "../BrushHeading";

const groups=[
  {number:"01",title:"Mobile mechanics",art:"/reference-headings/home-services/mobile-mechanics.png",icon:"/mobile-servicing.png",copy:"Straight-talking motorcycle maintenance and repairs at your home, workplace or another suitable location.",items:["Routine servicing and maintenance","Oil, filters and consumables","Safety and pre-ride checks","Mechanical repairs","Batteries, controls and lighting","Fault finding and diagnostics"]},
  {number:"02",title:"Breakdown assistance",art:"/reference-headings/home-services/breakdown-assistance.png",icon:"/reference-headings/home-services/emergency-recovery-beacon.png",copy:"Practical help when your bike will not start, has developed a fault or is no longer safe to ride.",items:["Roadside assessment","Starting and battery problems","Minor mobile repairs where safe","Clear advice on the next step","Member and non-member call-outs","Out-of-hours support subject to availability"]},
  {number:"03",title:"Recovery & transport",art:"/reference-headings/home-services/recovery-and-transport.png",icon:"/motorcycle-transport.png",copy:"Safe motorcycle collection when roadside repair is not possible, plus planned transport for moves, purchases and workshop visits.",items:["Motorcycle recovery","Home or workshop destination","MOT collection and return","Purchased-bike collection","Event and relocation transport","Secure loading and restraint"]}
];

const servicePlans=[
  {name:"Essential service",art:"/reference-headings/servicing/essential-service.png",image:"/servicing-images/essential-wheel.png",copy:"Routine oil and filter servicing with the key safety and maintenance checks.",price:"From £99"},
  {name:"Full service",art:"/reference-headings/servicing/full-service.png",image:"/servicing-images/full-engine.png",copy:"A more detailed inspection with additional maintenance and supported diagnostic checks.",price:"From £179"},
  {name:"Major service",art:"/reference-headings/servicing/major-service.png",image:"/servicing-images/major-piston.png",copy:"Manufacturer-scheduled maintenance tailored to the motorcycle, mileage, age and service history.",price:"From £299"}
];

export default function Services(){return <PageShell>
  <PageHero eyebrow="Mechanics · Breakdown · Recovery" title="Keeping riders moving." art="/reference-headings/home-services/keeping-riders-moving.png" copy="Professional mobile support for all makes, capacities and styles of motorcycle throughout Shropshire and surrounding areas." actions={<><Link className="button" href="/contact#email-enquiry">Register your interest ↗</Link><a className="ghost-button" href="tel:07709225038">Call 07709 225 038</a></>}/>
  <section className="service-showcase">{groups.map(g=><article id={g.number==="01"?"repairs":g.number==="02"?"diagnostics":"transport"} key={g.number}><div className="service-punk-icon"><img src={g.icon} alt=""/></div><div className="service-detail"><span>{g.number}</span><BrushHeading level={2} src={g.art} text={g.title}/><p>{g.copy}</p><ul>{g.items.map(item=><li key={item}>{item}</li>)}</ul><Link className="ghost-button" href="/contact#email-enquiry">Register interest</Link></div></article>)}</section>
  <section className="compact-services"><article id="battery"><BrushHeading level={2} src="/brand-phrases/battery-replacement.png" text="Battery replacement"/><p>Battery testing, replacement and environmentally responsible disposal of the old battery, subject to suitable battery availability.</p></article><article id="brakes"><BrushHeading level={2} src="/brand-phrases/brake-service-and-repair-v2.png" text="Brake service & repair"/><p>Brake inspection, servicing and repair for motorcycles where the work can be carried out safely at a suitable location. Parts are charged separately.</p></article></section>
  <section className="service-plans-preview"><div className="service-plans-heading"><p className="eyebrow">Service plans</p><BrushHeading level={2} src="/reference-headings/servicing/scheduled-servicing.png" text="Scheduled servicing"/><p>Choose from three clear service levels, with pricing structured by engine capacity and the work required for your motorcycle.</p></div><div className="service-plan-preview-grid">{servicePlans.map(plan=><article className="service-plan-preview-card" key={plan.name}><img src={plan.image} alt=""/><BrushHeading level={3} src={plan.art} text={plan.name}/><p>{plan.copy}</p><strong>{plan.price}</strong></article>)}</div><div className="service-plans-actions"><Link className="button" href="/servicing">View all service plans</Link><Link className="ghost-button" href="/contact#email-enquiry">Register service interest</Link></div></section>
  <section className="diagnostics-equipment" id="motorcycle-diagnostics"><div className="diagnostics-equipment-intro"><img src="/repairs-diagnostics.png" alt="Motorcycle diagnostic equipment icon"/><div><p className="eyebrow">Fault found. Not guessed.</p><BrushHeading level={2} src="/heading-repairs-diagnostics.png" text="Motorcycle diagnostics"/><p>Obsidian uses the TOPDON UltraDiag Moto 2 professional motorcycle diagnostic platform to communicate with compatible motorcycle control units. It helps identify electronic and system faults accurately before parts are replaced or further mechanical investigation begins.</p><p className="diagnostic-caveat">Coverage and available functions vary by motorcycle manufacturer, model, year, control unit and installed software.</p></div></div><div className="diagnostics-detail-grid"><article><h3>What it can do</h3><ul><li>Full-system scans on supported motorcycles</li><li>Read and clear diagnostic fault codes</li><li>Display live data from compatible control units</li><li>Retrieve ECU and vehicle information</li><li>Run supported active or bi-directional component tests</li><li>Carry out available service resets, adaptations and calibrations</li><li>Use DLC-location guidance and labelled motorcycle adapters</li></ul></article><article><h3>Why it helps</h3><p>Live data and active tests allow a technician to compare sensor information and command supported components—such as injectors, throttle actuators or cooling fans—to observe their response. This supports quicker fault isolation and reduces unnecessary parts replacement. A scan identifies reported faults; it does not replace mechanical testing, wiring checks or technician judgement.</p></article><article><h3>Diagnostic capabilities</h3><p>The TOPDON UltraDiag Moto 2 can access supported motorcycle control systems to carry out a complete electronic health check. Depending on the make, model and year, this may include engine management, fuel injection, ignition, ABS and braking, instrument and body-control systems.</p><p>It can retrieve and clear stored fault codes, display live sensor and actuator data, identify ECU information and run supported active tests. Available service functions can include maintenance resets, adaptations and calibrations, helping confirm the cause of a fault and guide the correct mechanical or electrical checks.</p></article><article className="diagnostic-pricing"><h3>Diagnostic pricing</h3><p><strong>Diagnostic scan</strong><span>From £45</span></p><p><strong>Full diagnostic report</strong><span>£65</span></p><p>Where deeper investigation is required, diagnostic labour is £50 for the first hour and £45 for each additional hour. Charges may be reduced or waived where resulting repair work is undertaken by Obsidian.</p><Link className="button" href="/contact#email-enquiry">Register diagnostic interest</Link></article></div></section>
  <section className="charges-section"><div><p className="eyebrow">Clear pricing</p><BrushHeading level={2} src="/reference-headings/home-services/know-the-basics-before-we-arrive.png" text="Know the basics before we arrive."/><p>Parts, materials and additional labour are charged separately. Planned motorcycle transport is quoted according to distance and requirements.</p></div><dl><div><dt>In-hours call-out</dt><dd>£80</dd></div><div><dt>Travel included</dt><dd>20 miles</dd></div><div><dt>Additional mileage</dt><dd>£1.50/mile</dd></div><div><dt>Out-of-hours surcharge</dt><dd>£30</dd></div><div><dt>Mobile labour</dt><dd>£45/hour</dd></div><div><dt>Out-of-hours labour</dt><dd>£60/hour</dd></div></dl></section>
  <section className="all-bikes-band"><div><p className="eyebrow">All bikes welcome</p><BrushHeading level={2} src="/reference-headings/home-services/different-machines-same-respect.png" text="Different machines. Same respect."/><p>Japanese, European, American or British. Modern, classic, custom or everyday transport. If the work can be carried out safely and within our capability, we’ll help. If it cannot, we’ll tell you honestly and help plan the right next step.</p><Link className="button" href="/contact#email-enquiry">Register your bike ↗</Link></div><img src="/obsidian-vtwin-support-icon.png" alt="Distressed V-twin motorcycle engine icon"/></section>
</PageShell>}
