import PageShell,{PageHero} from "../SiteChrome";
import BrushHeading from "../BrushHeading";

export default function Privacy(){return <PageShell>
  <PageHero eyebrow="Legal" title="Privacy notice" art="/reference-headings/forms-legal/privacy-notice.png" copy="How Obsidian Motorcycles Ltd collects, uses and protects personal information. Last updated 28 August 2026."/>
  <section className="legal-copy">
    <BrushHeading level={2} src="/reference-headings/forms-legal/who-we-are.png" text="Who we are"/>
    <p>Obsidian Motorcycles Ltd, company number 17416643, registered office 66 Lewis Crescent, Wellington, Telford, TF1 2FR, is the controller of personal information described in this notice. We are registered with the Information Commissioner’s Office under reference <strong>ZC229951</strong>. Contact our privacy lead at <a href="mailto:info@obsidianmotorcycles.com?subject=Data%20protection%20enquiry">info@obsidianmotorcycles.com</a> or 07709 225 038.</p>
    <BrushHeading level={2} src="/reference-headings/forms-legal/information-we-collect.png" text="Information we collect"/>
    <p>We may collect names, addresses, email addresses, telephone numbers, booking and communication records, motorcycle make, model, year, registration or VIN, ownership or authority evidence, service location, photographs, fault and job details, membership selections, payment and invoice status, Direct Debit references, membership cancellation requests and confirmations, complaints, marketing preferences and website or cookie choices.</p>
    <p>Where genuinely necessary to support a stranded or vulnerable customer, we may record limited accessibility, safety or health information provided by that person. We will minimise it and remove it when no longer needed unless an incident, claim or legal obligation requires retention.</p>
    <BrushHeading level={2} src="/reference-headings/forms-legal/why-we-use-it.png" text="Why we use it"/>
    <p>We process information to answer enquiries, prepare quotations, make and perform contracts, provide mechanics, diagnostics, recovery, transport and membership services, identify motorcycles, take payment, manage accounts, administer renewals and cancellations, keep safety and service records, prevent fraud, resolve complaints, comply with tax and legal duties, establish or defend legal claims, improve operations and—with a permitted basis—send marketing.</p>
    <h2>Lawful bases</h2>
    <ul><li><strong>Contract:</strong> to take requested steps and provide booked or membership services, including renewals and cancellations.</li><li><strong>Legal obligation:</strong> for accounting, tax, consumer, company, safety and law-enforcement duties.</li><li><strong>Legitimate interests:</strong> to operate safely, keep proportionate records, prevent fraud, manage complaints and improve services, balanced against individual rights.</li><li><strong>Consent:</strong> for optional electronic marketing and non-essential cookies where consent is required. Consent may be withdrawn at any time without affecting earlier lawful processing.</li><li><strong>Vital interests:</strong> exceptionally, to protect someone’s life where they cannot consent.</li></ul>
    <h2>Sensitive information</h2><p>Accessibility or health information is special category data. Where we genuinely need it to provide safe assistance, we will normally rely on explicit consent. In an emergency we may instead rely on vital interests where the person is physically or legally unable to consent. Information needed to establish, exercise or defend legal claims may be retained on that basis. We do not request more sensitive information than is necessary.</p>
    <h2>Where information comes from</h2>
    <p>Most information comes directly from customers, members or website visitors. We may also receive information from an authorised representative, motorcycle owner or registered keeper, recovery partner, payment provider, insurer, police or other authority, publicly available vehicle source, or referral partner where lawful.</p>
    <h2>Who we share it with</h2>
    <p>Where necessary and subject to suitable protections, information may be shared with Tide and other payment or Direct Debit providers including GoCardless; our accountant and accounting software; website and hosting providers including Netlify; Google Workspace; mailing-list and communications providers; recovery or transport subcontractors; parts suppliers where identification is needed; garages, MOT stations or destinations authorised by the customer; professional advisers and insurers; fraud-prevention services; police, courts, regulators and authorities where required; and a buyer or adviser involved in a lawful business reorganisation.</p>
    <p>We do not sell personal information. Payment card and bank details are processed by the payment provider and are not stored by Obsidian unless the provider makes limited reference or status information available to us.</p>
    <h2>International transfers</h2>
    <p>Some technology providers may process information outside the UK. Where this occurs, we will use an applicable UK adequacy decision, approved contractual safeguards or another lawful transfer mechanism.</p>
    <h2>How long we keep information</h2>
    <ul><li>Enquiries that do not become jobs: normally up to 12 months after the last contact.</li><li>Job, invoice, payment and accounting records: normally six years after the relevant financial period or contract ends.</li><li>Membership, renewal, cancellation and service-history records: normally six years after membership or the customer relationship ends.</li><li>Complaints, disputes, safety incidents and claims: normally six years after closure, or longer where a live claim or legal requirement applies.</li><li>Vehicle photographs: up to six years where part of a job, transport, damage or dispute record; otherwise normally deleted within 12 months.</li><li>Marketing records: until consent is withdrawn or the information is no longer useful, with a minimal suppression record retained to respect opt-outs.</li><li>Cookie preferences: for the period stated in the Cookie Policy or until reset.</li></ul>
    <p>These are normal periods. We may keep information for less time where it is no longer necessary, or longer where required for law, tax, safety, fraud prevention or legal claims.</p>
    <BrushHeading level={2} src="/reference-headings/forms-legal/marketing.png" text="Marketing"/>
    <p>Marketing choices are separate from service enquiries. We will send electronic marketing only where consent or another lawful PECR basis applies. Consent can be withdrawn at any time by using an unsubscribe option or emailing info@obsidianmotorcycles.com. Service, payment, renewal, cancellation and safety messages are not marketing.</p>
    <h2>Security</h2>
    <p>We use proportionate organisational and technical measures to protect information. No internet service is completely secure, but access is restricted to people and providers who need it for legitimate purposes.</p>
    <BrushHeading level={2} src="/reference-headings/forms-legal/your-rights.png" text="Your rights"/>
    <p>Depending on the circumstances, individuals may request access, correction, erasure, restriction, portability or objection; withdraw consent; and ask for review of certain automated decisions. To exercise a right, email info@obsidianmotorcycles.com. We may need to verify identity and normally respond within one month.</p>
    <h2>Automated decisions</h2><p>We do not currently make decisions with legal or similarly significant effects about customers or members using solely automated processing. If that changes, we will explain the logic, significance, likely consequences and available safeguards before using it.</p>
    <h2>Children</h2><p>People under 18 must ask a parent or guardian to enter a service or membership contract. We do not knowingly market directly to children.</p>
    <h2>Data protection complaints</h2><p>Email <a href="mailto:info@obsidianmotorcycles.com?subject=Data%20protection%20complaint">info@obsidianmotorcycles.com</a> with the subject “Data protection complaint”, or write to our registered office. We will acknowledge a data protection complaint within 30 days, take appropriate steps to investigate it without undue delay, keep the complainant informed and explain the outcome. You may also complain to the <a href="https://ico.org.uk/make-a-complaint/data-protection-complaints/">Information Commissioner’s Office</a>, Wycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF, or call 0303 123 1113.</p>
    <h2>Changes</h2><p>We may update this notice when services, providers or legal requirements change. The latest version and update date will be published here.</p>
  </section>
</PageShell>}
