import Link from "next/link";
import PageShell,{PageHero} from "../SiteChrome";

export default function Terms(){return <PageShell>
  <PageHero eyebrow="Legal" title="Terms & conditions" copy="General website and business terms for Obsidian Motorcycles Ltd. Last updated 27 August 2026."/>
  <section className="legal-copy">
    <h2>About us</h2><p>Obsidian Motorcycles Ltd is a company registered in England and Wales under company number 17416643. Our registered office is 66 Lewis Crescent, Wellington, Telford, TF1 2FR. Contact us at info@obsidianmotorcycles.com or 07709 225 038.</p>
    <h2>Website status</h2><p>This website provides information about our planned services and allows people to register interest. Until the launch notice is removed, information, availability and prices are provisional and may change. Submitting an enquiry does not create a confirmed booking or require us to accept work.</p>
    <h2>Using this website</h2><p>You may use this website for lawful personal or business enquiries. You must not misuse it, interfere with its operation, submit false information or attempt unauthorised access. Website availability is not guaranteed and content may be corrected, suspended or updated.</p>
    <h2>Service contracts</h2><p>A service contract is formed only when we clearly accept a booking or quotation. The scope, price or charging basis, location and timing communicated at acceptance form part of the contract. Our <Link href="/service-terms">Service Terms &amp; Conditions</Link> apply to mechanical work, diagnostics, recovery and transport. Separate <Link href="/membership-terms">Membership Terms</Link> apply to breakdown assistance memberships. Members can end their membership contract through the <Link href="/cancel-membership">online cancellation form</Link>; cancelling only a bank mandate may not update the membership record.</p>
    <h2>Prices and payment</h2><p>Published prices include VAT only where expressly stated and where VAT is applicable. Parts, materials, mileage, recovery, storage and additional labour may be charged separately where disclosed. Payment is due immediately after the service unless we approve written invoice terms, in which case payment is due within seven days.</p>
    <h2>Consumer rights</h2><p>Nothing in these terms excludes or restricts rights that cannot legally be excluded, including the right for services to be performed with reasonable care and skill and for supplied goods to be satisfactory, as described and fit for purpose where the law requires.</p>
    <h2>Intellectual property</h2><p>The Obsidian Motorcycles Ltd name, original branding, written content and original artwork on this website belong to Obsidian Motorcycles Ltd or are used with permission. Manufacturer names and marks remain the property of their respective owners and are used only to identify makes of motorcycle.</p>
    <h2>Liability</h2><p>We do not exclude liability where it would be unlawful, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation. Subject to that, we are not responsible for losses caused by inaccurate information supplied by a customer, unauthorised modifications, pre-existing faults, customer-supplied parts, misuse or events beyond our reasonable control.</p>
    <h2>Complaints</h2><p>Email complaints to info@obsidianmotorcycles.com. We aim to acknowledge complaints within five working days and provide a final response within 14 working days. If more time is required, we will explain why and provide an update. We are not currently subscribed to an alternative dispute resolution scheme.</p>
    <h2>Law</h2><p>These terms are governed by the law of England and Wales. Consumers retain any mandatory right to bring proceedings in the courts applicable to where they live.</p>
  </section>
</PageShell>}
